fos_rest:
  body_converter:
    enabled: true
  body_listener:
    array_normalizer: fos_rest.normalizer.camel_keys
  param_fetcher_listener: true
  serializer:
    serialize_null: true
  view:
    mime_types:
      json: ['application/json; charset=UTF-8', 'application/json']
    view_response_listener: true
    formats:
      json: true
      xml: false
  format_listener:
    enabled: true
    rules:
      - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: false }
