jms_serializer:
  property_naming:
    id: 'jms_serializer.identical_property_naming_strategy'
  metadata:
    directories:
      Article:
        namespace_prefix: "App\\Model\\Article"
        path: "%kernel.project_dir%/config/serializer/app/model/article"
      Author:
        namespace_prefix: "App\\Model\\Author"
        path: "%kernel.project_dir%/config/serializer/app/model/author"
