version: '3.9'

services:
  database:
    container_name: database
    image: mysql
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - db-app:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    networks:
      - zelty

  php:
    container_name: php
    build:
      context: './php'
    depends_on:
      - database
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ..:/app
    ports:
      - 9000:9000
    networks:
      - zelty

  nginx:
    build:
      context: './nginx'
    depends_on:
      - php
    ports:
      - 8080:80
      - 8081:81
    volumes:
      - ..:/app
    networks:
      - zelty

volumes:
  db-app:

networks:
  zelty:
